/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author bruno
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JDesktopPane();
        BarraMenu = new javax.swing.JMenuBar();
        MenuBtAtendimento = new javax.swing.JMenu();
        BtNovoAtendimento = new javax.swing.JMenuItem();
        BtListarAtendimentos = new javax.swing.JMenuItem();
        BtCadastrarCliente = new javax.swing.JMenuItem();
        MenuBtProcedimentos = new javax.swing.JMenu();
        MenuBtMed = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1920, 780));

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        BarraMenu.setBackground(java.awt.SystemColor.textHighlight);
        BarraMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarraMenu.setBorderPainted(false);
        BarraMenu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        BarraMenu.setPreferredSize(new java.awt.Dimension(406, 40));

        MenuBtAtendimento.setText("Atendimento");
        MenuBtAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtAtendimentoActionPerformed(evt);
            }
        });

        BtNovoAtendimento.setText("Novo Atendimento");
        BtNovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoAtendimentoActionPerformed(evt);
            }
        });
        MenuBtAtendimento.add(BtNovoAtendimento);

        BtListarAtendimentos.setText("Listar Atendimentos");
        BtListarAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtListarAtendimentosActionPerformed(evt);
            }
        });
        MenuBtAtendimento.add(BtListarAtendimentos);

        BtCadastrarCliente.setText("Cadastrar Novo Cliente");
        BtCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarClienteActionPerformed(evt);
            }
        });
        MenuBtAtendimento.add(BtCadastrarCliente);

        BarraMenu.add(MenuBtAtendimento);

        MenuBtProcedimentos.setText("Cadastro de Procedimentos");
        BarraMenu.add(MenuBtProcedimentos);

        MenuBtMed.setText("Estoque de Medicamentos");
        BarraMenu.add(MenuBtMed);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBtAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBtAtendimentoActionPerformed

    private void BtCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarClienteActionPerformed
        // TODO add your handling code here:
        
        CadastroCliente cadCliente = new CadastroCliente();
        Painel.add(cadCliente);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_BtCadastrarClienteActionPerformed

    private void BtNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoAtendimentoActionPerformed
        // TODO add your handling code here:
        
        NovoAtendimento NewAtend = new NovoAtendimento();
        Painel.add(NewAtend);
        NewAtend.setVisible(true);
    }//GEN-LAST:event_BtNovoAtendimentoActionPerformed

    private void BtListarAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtListarAtendimentosActionPerformed
        // TODO add your handling code here:
        
        ListarAtendimentos ListAtend = new ListarAtendimentos();
        Painel.add(ListAtend);
        ListAtend.setVisible(true);
    }//GEN-LAST:event_BtListarAtendimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BtCadastrarCliente;
    private javax.swing.JMenuItem BtListarAtendimentos;
    private javax.swing.JMenuItem BtNovoAtendimento;
    private javax.swing.JMenu MenuBtAtendimento;
    private javax.swing.JMenu MenuBtMed;
    private javax.swing.JMenu MenuBtProcedimentos;
    private javax.swing.JDesktopPane Painel;
    // End of variables declaration//GEN-END:variables
}
